// <auto-generated />
using System;
using CW21.Presentation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CW21.Presentation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529113709_bib")]
    partial class bib
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CW21.Presentation.Entities.Authors.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Romania",
                            FullName = "Jon Skeet"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Germany",
                            FullName = "Andrew Lock"
                        },
                        new
                        {
                            Id = 3,
                            Country = "France",
                            FullName = "Martin Fowler"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Italy",
                            FullName = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Poland",
                            FullName = "Julie Lerman"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.BookTags.BookTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            TagId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            TagId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            TagId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            TagId = 3
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            TagId = 1
                        },
                        new
                        {
                            Id = 7,
                            BookId = 3,
                            TagId = 5
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            TagId = 4
                        },
                        new
                        {
                            Id = 9,
                            BookId = 4,
                            TagId = 1
                        },
                        new
                        {
                            Id = 10,
                            BookId = 5,
                            TagId = 1
                        },
                        new
                        {
                            Id = 11,
                            BookId = 6,
                            TagId = 2
                        },
                        new
                        {
                            Id = 12,
                            BookId = 7,
                            TagId = 2
                        },
                        new
                        {
                            Id = 13,
                            BookId = 7,
                            TagId = 3
                        },
                        new
                        {
                            Id = 14,
                            BookId = 7,
                            TagId = 1
                        },
                        new
                        {
                            Id = 15,
                            BookId = 8,
                            TagId = 3
                        },
                        new
                        {
                            Id = 16,
                            BookId = 8,
                            TagId = 4
                        },
                        new
                        {
                            Id = 17,
                            BookId = 9,
                            TagId = 3
                        },
                        new
                        {
                            Id = 18,
                            BookId = 9,
                            TagId = 4
                        },
                        new
                        {
                            Id = 19,
                            BookId = 10,
                            TagId = 1
                        },
                        new
                        {
                            Id = 20,
                            BookId = 11,
                            TagId = 1
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 769, DateTimeKind.Utc).AddTicks(5931),
                            Price = 299.99m,
                            PublishYear = 2024,
                            PublisherId = 4,
                            Stock = 50,
                            Title = "EF Core Guide"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1577),
                            Price = 199.99m,
                            PublishYear = 2023,
                            PublisherId = 2,
                            Stock = 35,
                            Title = "ASP.NET Core Basics"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1586),
                            Price = 249.99m,
                            PublishYear = 2008,
                            PublisherId = 3,
                            Stock = 40,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1593),
                            Price = 279.99m,
                            PublishYear = 2018,
                            PublisherId = 1,
                            Stock = 20,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1654),
                            Price = 320.00m,
                            PublishYear = 2019,
                            PublisherId = 3,
                            Stock = 45,
                            Title = "C# in Depth"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1670),
                            Price = 180.50m,
                            PublishYear = 2022,
                            PublisherId = 4,
                            Stock = 28,
                            Title = "SQL Server Essentials"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1676),
                            Price = 310.75m,
                            PublishYear = 2021,
                            PublisherId = 2,
                            Stock = 18,
                            Title = "Entity Framework Mastery"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1683),
                            Price = 270.00m,
                            PublishYear = 2020,
                            PublisherId = 1,
                            Stock = 33,
                            Title = "Designing REST APIs"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1689),
                            Price = 350.00m,
                            PublishYear = 2024,
                            PublisherId = 3,
                            Stock = 22,
                            Title = "Microservices Fundamentals"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1700),
                            Price = 210.25m,
                            PublishYear = 2021,
                            PublisherId = 2,
                            Stock = 26,
                            Title = "LINQ Deep Dive"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1707),
                            Price = 330.00m,
                            PublishYear = 2022,
                            PublisherId = 1,
                            Stock = 31,
                            Title = "Advanced C#"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1713),
                            Price = 240.99m,
                            PublishYear = 2020,
                            PublisherId = 4,
                            Stock = 19,
                            Title = "NoSQL for Developers"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1719),
                            Price = 289.99m,
                            PublishYear = 2023,
                            PublisherId = 3,
                            Stock = 37,
                            Title = "Backend Development with .NET"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1726),
                            Price = 260.00m,
                            PublishYear = 2019,
                            PublisherId = 1,
                            Stock = 24,
                            Title = "Database Design Principles"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1733),
                            Price = 295.00m,
                            PublishYear = 2017,
                            PublisherId = 2,
                            Stock = 29,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1739),
                            Price = 205.50m,
                            PublishYear = 2021,
                            PublisherId = 4,
                            Stock = 17,
                            Title = "Practical Dependency Injection"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1745),
                            Price = 275.75m,
                            PublishYear = 2022,
                            PublisherId = 2,
                            Stock = 21,
                            Title = "Mastering PostgreSQL"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1755),
                            Price = 315.25m,
                            PublishYear = 2020,
                            PublisherId = 3,
                            Stock = 27,
                            Title = "Software Engineering Patterns"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1761),
                            Price = 285.40m,
                            PublishYear = 2024,
                            PublisherId = 1,
                            Stock = 32,
                            Title = "Building APIs with ASP.NET Core"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 11, 37, 5, 770, DateTimeKind.Utc).AddTicks(1768),
                            Price = 230.00m,
                            PublishYear = 2023,
                            PublisherId = 4,
                            Stock = 23,
                            Title = "Data Access in .NET"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Architecture"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Publishers.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "O'Reilly"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Manning"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apress"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Tags.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.BookTags.BookTag", b =>
                {
                    b.HasOne("CW21.Presentation.Entities.Books.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CW21.Presentation.Entities.Tags.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Books.Book", b =>
                {
                    b.HasOne("CW21.Presentation.Entities.Authors.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CW21.Presentation.Entities.Categories.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CW21.Presentation.Entities.Publishers.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Authors.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Books.Book", b =>
                {
                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Categories.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Publishers.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Tags.Tag", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
