// <auto-generated />
using System;
using CW21.Presentation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CW21.Presentation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521123841_EditPublisherData")]
    partial class EditPublisherData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CW21.Presentation.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1952,
                            Country = "USA",
                            FullName = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1963,
                            Country = "UK",
                            FullName = "Martin Fowler"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1961,
                            Country = "Switzerland",
                            FullName = "Erich Gamma"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1964,
                            Country = "USA",
                            FullName = "Andrew Hunt"
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = 1956,
                            Country = "USA",
                            FullName = "David Thomas"
                        },
                        new
                        {
                            Id = 6,
                            BirthYear = 1976,
                            Country = "UK",
                            FullName = "Jon Skeet"
                        },
                        new
                        {
                            Id = 7,
                            BirthYear = 1972,
                            Country = "USA",
                            FullName = "Scott Hanselman"
                        },
                        new
                        {
                            Id = 8,
                            BirthYear = 1962,
                            Country = "USA",
                            FullName = "Steve McConnell"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 700m,
                            PublishYear = 2008,
                            PublisherId = 1,
                            Stock = 0,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 650m,
                            PublishYear = 2017,
                            PublisherId = 1,
                            Stock = 3,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 720m,
                            PublishYear = 1999,
                            PublisherId = 3,
                            Stock = 5,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 690m,
                            PublishYear = 2002,
                            PublisherId = 3,
                            Stock = 16,
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 750m,
                            PublishYear = 1994,
                            PublisherId = 3,
                            Stock = 1,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 680m,
                            PublishYear = 1999,
                            PublisherId = 2,
                            Stock = 10,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 730m,
                            PublishYear = 2019,
                            PublisherId = 2,
                            Stock = 4,
                            Title = "The Pragmatic Programmer 20th Anniversary"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 710m,
                            PublishYear = 2019,
                            PublisherId = 4,
                            Stock = 2,
                            Title = "C# in Depth"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 690m,
                            PublishYear = 2020,
                            PublisherId = 3,
                            Stock = 3,
                            Title = "ASP.NET Core in Action"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 760m,
                            PublishYear = 2004,
                            PublisherId = 3,
                            Stock = 0,
                            Title = "Code Complete"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Programming and software engineering books",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Architecture and design books",
                            Name = "Software Architecture"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Clean coding practices",
                            Name = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Design patterns and best practices",
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = 5,
                            Description = "DevOps and software delivery",
                            Name = "DevOps"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Prentice Hall",
                            PhoneNumber = "111111111"
                        },
                        new
                        {
                            Id = 2,
                            City = "California",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "O'Reilly Media",
                            PhoneNumber = "222222222"
                        },
                        new
                        {
                            Id = 3,
                            City = "Boston",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Addison-Wesley",
                            PhoneNumber = "333333333"
                        },
                        new
                        {
                            Id = 4,
                            City = "Washington",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microsoft Press",
                            PhoneNumber = "444444444"
                        },
                        new
                        {
                            Id = 5,
                            City = "Birmingham",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packt Publishing",
                            PhoneNumber = "555555555"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Book", b =>
                {
                    b.HasOne("CW21.Presentation.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CW21.Presentation.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CW21.Presentation.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
